services:
  web:
    image: nginx:1.29.1 
    volumes:
      # Mount the application code for live updates
      - ./src:/var/www
      # Mount the Nginx configuration file
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # Map port 80 inside the container to the port specified by 'NGINX_PORT' on the host machine
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - laravel-development
    depends_on:
      php-fpm:
        condition: service_started  # Wait for php-fpm to start

  php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    env_file:
      # Load the environment variables from the Laravel application
      - ./src/.env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      # Mount the application code for live updates
      - ./src:/var/www
    networks:
      - laravel-development
    depends_on:
      mariadb:
        condition: service_started  # Wait for mariadb to start

  mariadb:
    image: mariadb:12.0.2
    ports:
      - "3306:3306"
    environment:
      - MARIADB_DATABASE=app
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=apppassword
      - MARIADB_ROOT_PASSWORD=rootpassword
    volumes:
      - "./docker/mariadb/GastroServeNow.sql:/docker-entrypoint-initdb.d/GastroServeNow.sql:ro"
    networks:
      - laravel-development

  redis:
    image: redis:alpine
    networks:
      - laravel-development

networks:
  laravel-development:
